spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true
      databaseName: "musicmanagerdb"

graphql:
  packages: "hu.simda.musicmanagerserver"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG